// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package button

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	twmerge "github.com/Oudwins/tailwind-merge-go/pkg/twmerge"
	"github.com/gungun974/gocva"
)

var M = twmerge.Merge

var cva = gocva.CVA{
	Base: `inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors
focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none
disabled:opacity-50`,
	Variants: gocva.Variants{
		"variant": {
			"default":     "bg-eGreen text-background hover:bg-eGreen/80",
			"destructive": "bg-eRed text-destructive-foreground hover:bg-eRed/80",
			"outline":     "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
			"secondary":   "bg-eYellow text-background hover:bg-eYellow/80 ring-eYellow focus-visible:border-eYellow",
			"ghost":       "hover:bg-accent hover:text-accent-foreground",
			"glass":       "border border-black/30 bg-black/5 backdrop-blur-md shadow-md hover:scale-90 transition-all transition-duration-300 active:bg-black/20",
			"link":        "text-primary hover:underline",
			"purple":      "bg-ePurple text-background hover:bg-ePurple/100",
		},
		"size": {
			"default":  "h-10 px-4 py-2",
			"sm":       "h-9 rounded-md px-3",
			"nav":      "h-3 w-10",
			"lg":       "h-11 rounded-md px-8",
			"readmore": "h-11 rounded-xs px-24 py-8 text-md",
			"icon":     "h-10 w-10",
			"iconlg":   "h-12 w-12",
			"iconsm":   "h-8 w-8",
			"iconxs":   "h-7 w-7",
		},
	},
	DefaultVariants: gocva.Variant{
		"variant": "default",
		"size":    "default",
	},
}

type Props struct {
	Class   string
	Attrs   templ.Attributes
	Variant gocva.Variant
}

func Button(props Props) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{M(cva.Render(props.Variant), props.Class)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<button class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/components/ui/button/button.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, props.Attrs)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
