// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package dummyTemplates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func frontArt() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div><div class=\"font-barlow\">Hello World!6</div><div class=\"\"><div class=\"h-auto w-full\" style=\"\" id=\"frontArtDiv\"><img src=\"/static/assets/Sixsix_MorningRoutine/Sixsix_MorningRoutine_0001.jpeg\" style=\"\" class=\"frontArt opacity-0 absolute\" id=\"frontArtId\"> <img src=\"/static/assets/Sixsix_MorningRoutine/Sixsix_MorningRoutine_0002.jpeg\" style=\"\" class=\"frontArt opacity-0 absolute\"> <img src=\"/static/assets/Sixsix_MorningRoutine/Sixsix_MorningRoutine_0002.jpeg\" style=\"\" class=\"frontArt opacity-0 absolute\"> <img src=\"/static/assets/Sixsix_MorningRoutine/Sixsix_MorningRoutine_0002.jpeg\" style=\"\" class=\"frontArt opacity-0 absolute\"> <img src=\"/static/assets/Sixsix_MorningRoutine/Sixsix_MorningRoutine_0002.jpeg\" style=\"\" class=\"frontArt opacity-0 absolute\"> <img src=\"/static/assets/Sixsix_MorningRoutine/Sixsix_MorningRoutine_0002.jpeg\" style=\"\" class=\"frontArt opacity-0 absolute\"></div><input id=\"rangeBar1\" type=\"range\" min=\"0\" max=\"100\" class=\"relative\"><h1 id=\"test\" class=\"relative\">1</h1></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func frontArtScript() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<script nonce=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.GetNonce(ctx))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/contents/frontArt/frontArt.templ`, Line: 28, Col: 37}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\">\n                document.addEventListener(\"mousemove\", function(event) {\n                const mouse = event.clientX;\n                document.getElementById(\"test\").textContent = mouse;\n                console.log(mouse);\n        })document.dispatchEvent(new Event(\"mousemove\"));\n\n        </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
